apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "task-system"
  name: "task-system"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "task-system"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "task-system"
    spec:
      containers:
        - image: docker.io/meirongdev/task-system:v0.0.11
          name: "task-system"
          command: ["/bin/sh"]
          args: ["/app/entrypoint.sh"]
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/.env.production
              name: task-system-env-local
              readOnly: true
              subPath: .env.production
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - configMap:
            # defaultMode: 420
            items:
              - key: .env
                path: .env.production
            name: task-system-env-local
          name: task-system-env-local
      restartPolicy: Always
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - jp
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "task-system"
  name: "task-system"
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: "task-system"
  sessionAffinity: None
